version: '3.7'

services:

  web:
    container_name: 'aspnetcoreapp'
    image: 'aspnetcoreapp'
    build:
      context: .
      dockerfile: aspnetcore.development.dockerfile
    volumes:
      - .:/var/www/aspnetcoreapp
    ports:
     - "5000:5000"
    networks:
      - aspnetcoreapp-network

networks:
  aspnetcoreapp-network:
    driver: bridge
